# Generated by Django 3.2.4 on 2021-07-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
    ]
